### ISSUE TITLE
Asynchronous spawn

### ISSUE THREAD

**Issue by sbalko** [adambom/parallel.js#102] opened 2015-05-09 00:25 UTC
Is there a way to use spawn in an asynchronous way? My use-case is unit testing: inside of the worker code I use requirejs to retrieve all dependencies before I then run any code. Hence, merely returning from the serialized function that is passed to spawn is not exactly an option. Instead, I would need to use a callback, which I call when my work is done and the worker can be terminated.

**Comment by Sebmaster** [comment] 2015-05-09 00:28
Duplicate of #39.

**Closed by Sebmaster** 2015-05-09 00:28 UTC

**Comment by Myzel394** [comment] 2020-10-19 19:58
Is there still no support for async 5 years later???
